# See https://simonwillison.net/2020/Oct/9/git-scraping/
name: "Build GSP"

on:
  workflow_dispatch:
  schedule:
    # Run once a day (arbitrary time chosen).
    - cron: "10 9 * * *"

jobs:
  build-gsp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Since we sometimes run `git push -f` to amend the most recent commit,
        # we need to be sure that we have the entire repository history when
        # doing so. If not, then we accidentally overwrite the entire
        # repository history with a single commit. Setting `fetch-depth: 0`
        # causes `actions/checkout@v2` to fetch the entire history, instead of
        # just the most recent commit.
        fetch-depth: 0
    - name: Install dependencies
      run: npm install
    - name: Build GSP
      run: ./bin/update-gsp.sh
